window.ImagerJsRussian = {
  'Incorrect file type': 'Неверный формат файла',
  'Insert': 'Вставить',
  'Cancel': 'Отмена',
  'Add image': 'Добавить изображение',
  'Quality': 'Качество',

  'Rotate': 'Поворот',
  'Crop': 'Обрезать',

  'Original': 'Оригинал',
  'KB': 'KB',
  'Large': 'Лучшее',
  'Medium': 'Среднее',
  'Small': 'Плохое',
  'Custom quality percent': 'Качество картинки',
  'Custom': 'Выбрать вручную',

  'Image properties': 'Свойства изображения',
  'Size:': 'Размер:',
  'width in px': 'ширина в пикселях',
  'height in px': 'высота в пикселях',
  'Left': 'Слева',
  'Right': 'Справа',
  'Center': 'По центру',
  'Inline': 'В тексте',
  'Floating': 'Плавающее',
  'Transparent background': 'Прозрачный фон',
  'Apply': 'Применить',
  'Reject': 'Отменить',
  'Delete image': 'Удалить изображение',
  'Move image': 'Двигать изображение',
  'Are you sure want to delete this image?': 'Вы уверены, что хотите удалить это изображение?',
  'Or drop files here': 'Или перетащите файл сюда',
  'No file selected.': 'Файл не выбран.',
  'Please wait...': 'Пожалуйста, подождите...',
  'Save': 'Сохранить',
  'Undo': 'Отменить',
  'Rotate manually': 'Вращать',
  'Rotate 90 left': 'Повернуть на 90° влево',
  'Rotate 90 right': 'Повернуть на 90° вправо',

  'Image is too big and could cause very poor performance.': 'Image is too big and could cause very poor performance.'
};